### ISSUE TITLE
Save event misbehaving on Android

### ISSUE THREAD

**Issue by Xirion11** [IntoTheDev/Save-System-for-Unity#1]
It seems the SaveFile method is not being called reliably on Android, at least when killing the app from the task manager which is the most used method on Android.

I don't think a fix or change in code would be needed since it works perfectly in the editor and most probably on standalone games. Maybe just add a section in the README.md that points this out so others know what is probably happening on Android.

What I did to fix it in my game was to add the call to SaveFile immediately after the Save method instead of waiting until the application quitting event.

**Comment by IntoTheDev** [comment]
Hi! Thank you very much for pointing it out! I will release a new version soon and will fix this issue.

**Comment by IntoTheDev** [comment]
Done! I suggest you to update the package since fixed version is better performance wise than your currently one.
