### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by whynames** [IntoTheDev/Save-System-for-Unity#10]
It doesn't work in Iphone build. Any idea why? Seems like it can't deserialize bytes

**Comment by whynames** [comment]
By the way, I saw there is a similar question in closed issues, you said it is fixed in new version, but I am using the last version already. I also added my functions to the project, so I can't easily switch to messagepack version
            `var data = SerializationUtility.DeserializeValue<T>(bytes, DATA_FORMAT, _deserializationContext);`
I placed debug lines between almost every line. Problem is here, after this line code stops and no more log.
Test is on IphonePlayer, and IL2CPP, which seems like the only options since it is greyed out

**Comment by IntoTheDev** [comment]
Does it work in editor or android? Any logs or sample project that you can provide? I don't have an iOS device so it would be hard to fix if it's iOS only bug.

**Comment by whynames** [comment]
I can't test on android, but It works in editor and mac build.

> `Creating a serialization formatter for the type 'UnityEngine.Vector3[]' failed due to missing AOT support. 
> 
>  Please use Odin's AOT generation feature to generate an AOT dll before building, and MAKE SURE that all of the following types were automatically added to the supported types list after a scan (if they were not, please REPORT AN ISSUE with the details of which exact types the scan is missing and ADD THEM MANUALLY): 
> 
> UnityEngine.Vector3[] (name string: 'UnityEngine.Vector3[], UnityEngine.CoreModule')
> 
> IF ALL THE TYPES ARE IN THE SUPPORT LIST AND YOU STILL GET THIS ERROR, PLEASE REPORT AN ISSUE.The exception contained the following message: 
> Attempting to call method 'ToolBox.Serialization.OdinSerializer.ArrayFormatter`1[[UnityEngine.Vector3, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]::.cctor' for which no ahead of time (AOT) code was generated.
> UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:LogError(Object)
> ToolBox.Serialization.OdinSerializer.FormatterLocator:LogAOTError(Type, Exception)
> ToolBox.Serialization.OdinSerializer.FormatterLocator:GetFormatter(Type, ISerializationPolicy)
> ToolBox.Serialization.OdinSerializer.FormatterLocator:GetFormatter(ISerializationPolicy)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:GetBaseFormatter(ISerializationPolicy)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.Serializer`1:ReadValueWeak(IDataReader)
> ToolBox.Serialization.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(T&, IDataReader)
> ToolBox.Serialization.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.DerivedDictionaryFormatter`3:DeserializeImplementation(TDictionary&, IDataReader)
> ToolBox.Serialization.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(Stream, DataFormat, DeserializationContext)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(Byte[], DataFormat, DeserializationContext)
> ToolBox.Serialization.MyDataSerializer:Deserialize(Byte[])
> ToolBox.Serialization.<LoadBinaryFile>d__20`1:MoveNext()
> Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
> System.Threading.Tasks.<>c:<.cctor>b__7_0(Object)
> UnityEngine.WorkRequest:Invoke()
> UnityEngine.UnitySynchronizationContext:Exec()
> UnityEngine.UnitySynchronizationContext:ExecuteTasks()
> 
> Data layout mismatch; skipping past node boundary when exiting array.
> UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:LogError(Object)
> ToolBox.Serialization.OdinSerializer.CustomLogger:LogError(String)
> ToolBox.Serialization.OdinSerializer.DebugContext:LogError(String)
> ToolBox.Serialization.OdinSerializer.BinaryDataReader:ExitArray()
> ToolBox.Serialization.OdinSerializer.DerivedDictionaryFormatter`3:DeserializeImplementation(TDictionary&, IDataReader)
> ToolBox.Serialization.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(Stream, DataFormat, DeserializationContext)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(Byte[], DataFormat, DeserializationContext)
> ToolBox.Serialization.MyDataSerializer:Deserialize(Byte[])
> ToolBox.Serialization.<LoadBinaryFile>d__20`1:MoveNext()
> Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
> System.Threading.Tasks.<>c:<.cctor>b__7_0(Object)
> UnityEngine.WorkRequest:Invoke()
> UnityEngine.UnitySynchronizationContext:Exec()
> UnityEngine.UnitySynchronizationContext:ExecuteTasks()`
> 

And this:

> `Creating a serialization formatter for the type 'UnityEngine.Vector3[]' failed due to missing AOT support. 
> 
>  Please use Odin's AOT generation feature to generate an AOT dll before building, and MAKE SURE that all of the following types were automatically added to the supported types list after a scan (if they were not, please REPORT AN ISSUE with the details of which exact types the scan is missing and ADD THEM MANUALLY): 
> 
> UnityEngine.Vector3[] (name string: 'UnityEngine.Vector3[], UnityEngine.CoreModule')
> 
> IF ALL THE TYPES ARE IN THE SUPPORT LIST AND YOU STILL GET THIS ERROR, PLEASE REPORT AN ISSUE.The exception contained the following message: 
> Attempting to call method 'ToolBox.Serialization.OdinSerializer.ArrayFormatter`1[[UnityEngine.Vector3, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]::.cctor' for which no ahead of time (AOT) code was generated.
> UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:LogError(Object)
> ToolBox.Serialization.OdinSerializer.FormatterLocator:LogAOTError(Type, Exception)
> ToolBox.Serialization.OdinSerializer.FormatterLocator:GetFormatter(Type, ISerializationPolicy)
> ToolBox.Serialization.OdinSerializer.FormatterLocator:GetFormatter(ISerializationPolicy)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:GetBaseFormatter(ISerializationPolicy)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.Serializer`1:ReadValueWeak(IDataReader)
> ToolBox.Serialization.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(T&, IDataReader)
> ToolBox.Serialization.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.DerivedDictionaryFormatter`3:DeserializeImplementation(TDictionary&, IDataReader)
> ToolBox.Serialization.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(Stream, DataFormat, DeserializationContext)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(Byte[], DataFormat, DeserializationContext)
> ToolBox.Serialization.MyDataSerializer:Deserialize(Byte[])
> ToolBox.Serialization.<LoadBinaryFile>d__20`1:MoveNext()
> Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
> System.Threading.Tasks.<>c:<.cctor>b__7_0(Object)
> UnityEngine.WorkRequest:Invoke()
> UnityEngine.UnitySynchronizationContext:Exec()
> UnityEngine.UnitySynchronizationContext:ExecuteTasks()
> 
> Data layout mismatch; skipping past node boundary when exiting array.
> UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:LogError(Object)
> ToolBox.Serialization.OdinSerializer.CustomLogger:LogError(String)
> ToolBox.Serialization.OdinSerializer.DebugContext:LogError(String)
> ToolBox.Serialization.OdinSerializer.BinaryDataReader:ExitArray()
> ToolBox.Serialization.OdinSerializer.DerivedDictionaryFormatter`3:DeserializeImplementation(TDictionary&, IDataReader)
> ToolBox.Serialization.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
> ToolBox.Serialization.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(IDataReader)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(Stream, DataFormat, DeserializationContext)
> ToolBox.Serialization.OdinSerializer.SerializationUtility:DeserializeValue(Byte[], DataFormat, DeserializationContext)
> ToolBox.Serialization.MyDataSerializer:Deserialize(Byte[])
> ToolBox.Serialization.<LoadBinaryFile>d__20`1:MoveNext()
> Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
> System.Threading.Tasks.<>c:<.cctor>b__7_0(Object)
> UnityEngine.WorkRequest:Invoke()
> UnityEngine.UnitySynchronizationContext:Exec()
> UnityEngine.UnitySynchronizationContext:ExecuteTasks()`

Seems like it is the problem, but I already tried generating the dll. Similar error for UnityEngine.Vector3[] and System.float[]. Maybe problem with arrays? Log file is longer  but too many unrelated stuff as you might guess. Error Xcode log file not supported to drag

**Comment by IntoTheDev** [comment]
Did you create `ITypeProvider`? In ur case something like this:

```csharp
using System;
using System.Collections.Generic;
using ToolBox.Serialization;
using UnityEngine;

public sealed class TestProvider : ITypeProvider
{
    public Type[] GetTypes()
    {
        return new Type[]
        {
            typeof(Vector3[]),
        };
    }
}
```

**Comment by whynames** [comment]
Thank you very much. I had done, but turns out I had too many types that I should include, also I didn't think arrays should be included separetely. More types makes it slower I guess since it was kinda slow, but it works.

**Comment by IntoTheDev** [comment]
I believe Odin Serializer made version that makes ITypeProvider unnecessary but I didn't check it yet.
