### ISSUE TITLE
Doesn't work for Android build settings

### ISSUE THREAD

**Issue by jamesT232** [IntoTheDev/Save-System-for-Unity#3]
Good day and thanks a lot on your work (Save system for unity)

There has been an issue, as it displays for android build.
Assets\Save-System-for-Unity-master\OdinSerializer\Utilities\Misc\EmitUtilities.cs(20,8): error CS1029: #error: 'Odin Inspector is incapable of compiling source code against the .NET Standard 2.0 API surface. You can change the API Compatibility Level in the Player settings.'

**Comment by IntoTheDev** [comment]
Hi! You can change the API Compatibility Level in the Player settings or you can try **messagepack** branch. This error tied directly to Odin Inspector.
![image](https://user-images.githubusercontent.com/53948684/208964914-e723bf47-f2e8-4e99-a354-2c2c2c7a8d7d.png)

**Comment by jamesT232** [comment]
Thank so much, you guys plugin as being really helpful to me as a college student
