### ISSUE TITLE
Does it work in editor mode? I couldn't make it work?

### ISSUE THREAD

**Issue by whynames** [IntoTheDev/Save-System-for-Unity#6]
Does it work in editor mode? I couldn't make it work? It gives null error in this line:

  if (_data.TryGetValue(key, out var data))

DataSerializer 26

**Comment by IntoTheDev** [comment]
It's should work in editor. Won't work without play mode tho because initialization happens via [RuntimeInitializeOnLoadMethod](https://docs.unity3d.com/ScriptReference/RuntimeInitializeOnLoadMethodAttribute.html)

**Comment by IntoTheDev** [comment]
I won't work on this as I don't see it as a useful feature at the moment, but feel free to create a fork/merge request.

**Comment by sandsalamand** [comment]
@IntoTheDev  Can you give us a hint for how to modify it to work in the Editor? I tried simply swapping RuntimeInitializeOnLoadMethod for InitializeOnLoadMethod, but that didn't work. From debugging, it seems like FormatterCache will never contain your Formatter. Is it possibly a load order issue, or does everything load after DataSerializer.Setup?

**Comment by whynames** [comment]
you can call setup function in static constructor

**Comment by sandsalamand** [comment]
@whynames ~~That doesn't work for me. Was that the only thing you needed to change?~~
Nevermind, I also had to change MessagePackStartup.Initialize to InitializeOnLoadMethod, and it works now.
