### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by sandsalamand** [IntoTheDev/Save-System-for-Unity#7]
Hello, I'm planning to fork your repository (messagepack branch) and add WebGL support using UnityWebRequest instead of System.IO. Is there anything that I need to know before doing so? And also, would you prefer if the new branch supported both WebGL and other platforms using preprocessor statements, or should I just make it a completely separate branch?

**Comment by IntoTheDev** [comment]
Hi! I tried messagepack branch in my WebGL project a while ago and managed to make it work via these changes:

```csharp
using MessagePack;
using MessagePack.Resolvers;
using MessagePack.Unity;
using MessagePack.Unity.Extension;
using Serializer;
using ToolBox.Serialization;
using UnityEngine;

namespace MessagePackGenerator
{
    public static class MessagePackStartup
    {
        private static bool _serializerRegistered;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void Initialize()
        {
            if (_serializerRegistered)
            {
                return;
            }

            StaticCompositeResolver.Instance.Register(
                GeneratedResolver.Instance,
                UnityBlitResolver.Instance,
                UnityResolver.Instance,
                StandardResolver.Instance,
                DataSerializerResolver.Instance
            );

            MessagePackSerializer.DefaultOptions = DataSerializer.Options;

            _serializerRegistered = true;
        }
    }
}
```

```csharp
using System;
using System.Collections.Generic;
using MessagePack;
using MessagePack.Formatters;

namespace Serializer
{
    public class DataSerializerResolver : IFormatterResolver
    {
        public static readonly IFormatterResolver Instance = new DataSerializerResolver();

        private DataSerializerResolver()
        {
        }

        public IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var formatter = DataSerializerResolverGetFormatterHelper.GetFormatter(typeof(T));

                if (formatter != null)
                {
                    Formatter = (IMessagePackFormatter<T>)formatter;
                }
            }
        }
    }

    internal static class DataSerializerResolverGetFormatterHelper
    {
        private static readonly Dictionary<Type, int> _lookup = new()
        {
            { typeof(Dictionary<string, byte[]>), 0 },
        };

        internal static object GetFormatter(Type t)
        {
            if (!_lookup.TryGetValue(t, out var key))
            {
                return null;
            }

            return key switch
            {
                0 => new DictionaryFormatter<string, byte[]>(),
                _ => null,
            };
        }
    }
}
```

```csharp
        public static void SaveFile(string fileName)
        {
            var path = CreatePath(fileName);
            var bytes = Serialize(_data);

            File.WriteAllBytes(path, bytes);
            
#if UNITY_WEBGL
            Application.ExternalEval("_JS_FileSystem_Sync();");
#endif
        }
        
        public static async Task SaveFileAsync(string fileName, CancellationToken token = default)
        {
            var path = CreatePath(fileName);
            var bytes = Serialize(_data);

            await File.WriteAllBytesAsync(path, bytes, token);
            
#if UNITY_WEBGL
            Application.ExternalEval("_JS_FileSystem_Sync();");
#endif
        }
```

I didn't upload them yet since currently I'm working on a desktop project and didn't use save system for a while. I'd glad to see your version too because I'm not so experienced with WebGL.

**Comment by IntoTheDev** [comment]
#8

**Comment by sandsalamand** [comment]
@IntoTheDev Did you test that branch on an actual build? It works fine in the editor, but the file loading fails when running on a browser.

The documentation says that you need to use UnityWebRequest to interact with the file system when running on the browser; have you found contradictory information?

**Comment by sandsalamand** [comment]
Ok, [StreamingAssets](https://docs.unity3d.com/Manual/StreamingAssets.html) requires you to use UnityWebRequest to access it, but since you're using Application.persistentDataPath, System.IO should work. Let me investigate a little bit more. It's very hard to debug WebGL builds because the stack trace gets mangled by IL2CPP.

**Comment by IntoTheDev** [comment]
It works just fine with **one** build but when you make another build new `Application.persistentDataPath` is generated and now your "game progression is lost".

**Comment by sandsalamand** [comment]
I'm getting an error in MessagePack at `GetFormatterWithVerify` where the formatter is returning null from `resolver.GetFormatter<T>()`

Based on a bunch of Debug statements, it seems that MessagePack is having no trouble serializing simple data like Vector3, but fails when you feed it the Dictionary when `SaveFile` is called.

Also, may I ask why you're serializing the data twice, once into bytes which you put in the dictionary at `DataSerializer.Save`, and then once again when `DataSerializer.SaveFile` is called? Is that a standard practice with MessagePack? I've never used it before.

**Comment by IntoTheDev** [comment]
> I'm getting an error in MessagePack at GetFormatterWithVerify where the formatter is returning null from resolver.GetFormatter<T>()
> 
> Based on a bunch of Debug statements, it seems that MessagePack is having no trouble serializing simple data like Vector3, but fails when you feed it the Dictionary when SaveFile is called.

Hmm, could you make a sample project for me? Changes from pull request worked just fine in Editor, WebGL build, desktop Mono and IL2CPP builds. Did you make DataSerializerResolver and registered it like I did in MessagePackStartup?

> Also, may I ask why you're serializing the data twice, once into bytes which you put in the dictionary at DataSerializer.Save, and then once again when DataSerializer.SaveFile is called? Is that a standard practice with MessagePack? I've never used it before.

IIRC Dictionary inside `DataSerializer` looked like this a some time ago: `Dictionary<string, object>`. But if you saved class via `DataSerializer.Save` and then modified that class it also gets modified in `DataSerializer._data` which is really undesired behaviour. Now I'm just serializing directly into dictionary and then writing all that bytes into file.

**Comment by sandsalamand** [comment]
Yes, I did register in MessagePackStartup.

Here is the sample project that crashes when built and ran
https://github.com/sandsalamand/Unity-WebGL-Save-System-Test

**Comment by IntoTheDev** [comment]
My bad, code above that you copied won't work with new pull request. Copy code below and see if it works now.

```csharp
using MessagePack;
using MessagePack.Resolvers;
using MessagePack.Unity;
using MessagePack.Unity.Extension;
using Serializer;
using ToolBox.Serialization;
using UnityEngine;

namespace MessagePackGenerator
{
	public static class MessagePackStartup
	{
		private static bool _serializerRegistered;

		[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
		private static void Initialize()
		{
			if (_serializerRegistered)
			{
				return;
			}

			StaticCompositeResolver.Instance.Register(
				//GeneratedResolver.Instance,
				UnityBlitResolver.Instance,
				UnityResolver.Instance,
				StandardResolver.Instance,
				DataSerializerResolver.Instance
			);

			var options = ContractlessStandardResolverAllowPrivate.Options.WithResolver(StaticCompositeResolver.Instance);
        
			DataSerializer.Options = options;
			MessagePackSerializer.DefaultOptions = options;

			_serializerRegistered = true;
		}
	}
}
```

**Comment by sandsalamand** [comment]
Yep, that fixed it. Thanks!

**Comment by sandsalamand** [comment]
Oh, and about the double serialization, how much of a performance impact is that having? Have you considered only allowing Struct serialization?
