### ISSUE TITLE
AOT Annoyances

### ISSUE THREAD

**Issue by sandsalamand** [IntoTheDev/Save-System-for-Unity#9]
Situation: building for an AOT platform using vlad/messagepack/webgl branch

Any time I add a new class or struct to be serialized, I have to go through the Unity MessagePack window and re-generate formatters, then I have to manually add `using UnityEngine;` to each script to make them recognize Unity types like Vector3. Am I doing something wrong, or is this just something I need to get used to?

**Comment by IntoTheDev** [comment]
Hi! 

Yeah, I'm met this problem too. My solution was to add namespace directly to field. Something like this:

```csharp
[MessagePackObject]
public class Data
{
    [Key(0)] public UnityEngine.Vector3 Position;
}
```

**Comment by sandsalamand** [comment]
Oh, of course. Thanks!
